def ex_6():
    # IOError catches exception related to IO
    # ZeroDivisionError catches exception of dividing by zero
    pass
